version: '3'
services:
  db:
    image: postgres:13
    container_name: product_service_db
    ports:
      - 6543:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product-service
