version: '3'
services:
  app:
    build: .
    image: product-service
    container_name: product_service_app
    depends_on:
      - db
    ports:
    - 8080:8080

  db:
    image: postgres:13
    container_name: product_service_db
    ports:
      - 6543:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product-service
    volumes:
      - ./products.json:/app-data/products.json
