create table products
(
    id bigint generated by default as identity constraint products_pkey primary key,
    category varchar(3) not null,
    currency varchar(5) not null,
    last_update timestamp not null default current_timestamp,
    name varchar(200) not null,
    price numeric(19,2) not null
);

create or replace function update_last_update_column()
returns trigger as $$
begin
   new.last_update = now();
return new;
end;
$$ language 'plpgsql';

create trigger update_products_last_update
    before update
    on products
    for each row execute procedure update_last_update_column();
